### PR TITLE
Adding turbolinks compatibility

### PR DESCRIPTION
**Pull request by rfsbsb**
This patch adds turbolinks compatibility

### CODE REVIEW

**Comment by yld** [comment]
+1 but the call to ready or on('someting',... should be left to user's decision, as we can choose to trigger typeahead on others (custom) event.

**Comment by inopinatus** [comment]
This is a) surely unnecessary if using the jquery turbolinks plugin and b) risks a race condition with the ready event, that jQuery's .ready method corrects for.

**Comment by crivotz** [comment]
Jquery.turbolinks is deprecated and with Turbolinks 5 is better use 
```
$(document).on('turbolinks:load', function() {
```

**Comment by maxivak** [comment]
see new gem version 0.2.3

include init file in application.js

for Turbolinks:
```
//= require jquery2
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead.min
//= require bootstrap3-autocomplete-input
//= require bootstrap3-autocomplete-input-init-turbolinks

```

**Pull request closed without merging**
