### PR TITLE
Added Turbolinks 5 compatibility

### PR DESCRIPTION
**Pull request by crivotz**

### CODE REVIEW

**Review by maxivak — COMMENTED** [review]
will it work without Turbolinks?

**Comment by crivotz** [comment]
No, that's why I closed the pull request. Thank you for responding and for the gem

**Comment by maxivak** [comment]
we need to make it work with or without Turbolinks without changing anything for users.

**Comment by maxivak** [comment]
added support for Turbolinks in new version 0.2.3:


application.js for Turbolinks:
```
//= require jquery2
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead.min
//= require bootstrap3-autocomplete-input
//= require bootstrap3-autocomplete-input-init-turbolinks

```

if you are not using Turbolinks:

```
//= require jquery2
//= require jquery_ujs
//= require bootstrap
//= require bootstrap3-typeahead.min
//= require bootstrap3-autocomplete-input
//= require bootstrap3-autocomplete-input-init

```

see Readme

**Pull request closed without merging**
